### ISSUE TITLE
VPC bin style and strat.facet don't work at the same time

### ISSUE THREAD

**Issue by margoal1** [ggPMXdevelopment/ggPMX#105]
**this works:**
`ctr %>% pmx_plot_vpc(bin = pmx_vpc_bin(style = "kmeans", n = 10))`

**this works:**
`ctr %>% pmx_plot_vpc(strat.facet = "STUD")`

**this doesn't work:**
`ctr %>% pmx_plot_vpc(bin = pmx_vpc_bin(style = "kmeans", n = 10), strat.facet = "STUD")`

```
Error in vecseq(f__, len__, if (allow.cartesian || notjoin || !anyDuplicated(f__,  : 
  Join results in 420 rows; more than 243 = nrow(x)+nrow(i). Check for duplicate key values in i each of which join to the same group in x over and over again. If that's ok, try by=.EACHI to run j for each group to avoid the large allocation. If you are sure you wish to proceed, rerun with allow.cartesian=TRUE. Otherwise, please search for this error message in the FAQ, Wiki, Stack Overflow and data.table issue tracker for advice.
```

**Comment by ggPMXdevelopment** [comment]
Yes, I just ran in the same issue, same error. This is very important, otherwise VPC is totally useless when dealing with more than one study.

**Comment by baltcir1** [comment]
Hint: use "within_strats = TRUE" argument of pmx_plot_vpc. It should work, but it's not all right yet. We are working on it.

**Comment by sehamsick** [comment]
I think I need to elaborate a little on the comment of baltcir1: the argument: **within_strats = TRUE has to be specified within pmx_vpc_bin()**, see example:

**This should work:**
ctr4 %>% pmx_plot_vpc(bin = pmx_vpc_bin(style = "kmeans", n = 10, **within_strat = TRUE**), strat.facet = "STUD")

within_stats = TRUE will be the new standard, a new ggPMX-version will be available soon.

**Some other hints:**
- **n** can be left out, is not mandatory to specify
- Try different style options to find the best fit: **"fixed", "sd", "equal", "pretty", "quantile", "kmeans", "hclust" or "jenks"**
- Adding **facets=list(scales="free")** (or "free_x","free_y", respectively), can be used to allow for variable x-y axes.
e.g. ctr4 %>% pmx_plot_vpc(bin = pmx_vpc_bin(style = "kmeans", n = 10, within_strat = TRUE), strat.facet = "STUD",
                                                                                                                                                          **facets=list(scales="free")** )

**Comment by baltcir1** [comment]
It still doesn't work. Example:
ctr2 = theophylline()
ctr2 %>% pmx_plot_vpc(bin = pmx_vpc_bin(style = "kmeans",n=5),
                          rug = pmx_vpc_rug(show=TRUE, color="black"),
                          filter = TIME<20,
                          strat.facet = ~STUD, 
                          within_strat = TRUE,
                          is.legend = FALSE,
                          facets=list(scales="free"),
                          scale_y_log10 = TRUE)

In the statement above, the following option do not work:
- rug = pmx_vpc_rug(show=TRUE, color="black"), we can't see the rugs anymore

Then, if we add is.footnote = FALSE (trying to remove the text on the bottom of the figure), we get the following error:
Error: p is not an object of class 'ggplot'.

If we further try to modify the binning and combine with a filter, I get the following error with theophilline:
ctr2 %>% pmx_plot_vpc(bin = pmx_vpc_bin(style = "fixed", fixedBreaks=c(0,2,4,6,8,10,12,14,16,18,20)),
                          filter = TIME<20,
                          strat.facet = ~STUD, 
                          facets=list(scales="free"),
                          scale_y_log10 = TRUE)
Error in factor(vals, levels = unique(vals), labels = labels) : 
  invalid 'labels'; length 11 should be 1 or 10
In addition: Warning message:
In (function (var, n, style = "quantile", rtimes = 3, ..., intervalClosure = c("left",  :
  n same as number of different finite values\neach different finite value is a separate class

On a "real" project, I actually can't used the the fixed binning and stratifying:
ctr %>% pmx_plot_vpc(bin = pmx_vpc_bin(style = "fixed", fixedBreaks=c(0,7,14,21,28,36,50,74,90,100,200)),
                         filter = TIME<100,
                         strat.facet = ~STUDYID, 
                         facets=list(scales="free"),
                         scale_y_log10 = TRUE)
Error in vecseq(f__, len__, if (allow.cartesian || notjoin || !anyDuplicated(f__,  : 
  Join results in 405 rows; more than 210 = nrow(x)+nrow(i). Check for duplicate key values in i each of which join to the same group in x over and over again. If that's ok, try by=.EACHI to run j for each group to avoid the large allocation. If you are sure you wish to proceed, rerun with allow.cartesian=TRUE. Otherwise, please search for this error message in the FAQ, Wiki, Stack Overflow and data.table issue tracker for advice.

Same error if I use (in my real project) binning style "kmeans" and try to stratify with strat.facet. The filter works fine on non-stratified (and on stratified when we manage to find a binning that works).
ctr %>% pmx_plot_vpc(bin = pmx_vpc_bin(style = "kmeans", n=30),
                         filter = TIME<100,
                         strat.facet = ~STUDYID, 
                         scale_y_log10 = TRUE)
Error in vecseq(f__, len__, if (allow.cartesian || notjoin || !anyDuplicated(f__,  : 
  Join results in 783 rows; more than 504 = nrow(x)+nrow(i). Check for duplicate key values in i each of which join to the same group in x over and over again. If that's ok, try by=.EACHI to run j for each group to avoid the large allocation. If you are sure you wish to proceed, rerun with allow.cartesian=TRUE. Otherwise, please search for this error message in the FAQ, Wiki, Stack Overflow and data.table issue tracker for advice.

**Comment by tynsci** [comment]
- Have split two of the bugs reported here (is.footnote, and rugs) into separate issues:
    - #216 
    - #217 

- Re: the problem with label length of factor for binning, this is already being addressed:
     - #201

- Re: duplicate keys error, suggest to open as a new issue if/when reproducible example is available
