### ISSUE TITLE
Monolix2020 compatibility

### ISSUE THREAD

**Issue by baltcir1** [ggPMXdevelopment/ggPMX#171]
Error is being produced when using pmx_mlxtran on a project created with Monolix2020. 

**To Reproduce**
ctr = pmx_mlxtran("MLX/PK_WITH_COVARIATE/warfarin_PK_project_mlx2020.mlxtran")

![image](https://user-images.githubusercontent.com/25454764/114690821-5c1ac900-9d17-11eb-8dff-38c58542078f.png)

The dataset is not being recognized by the reader. The issue comes from the fact that the statement containing the dataset of Monolix2020 does not have spaces, which makes ggPMX reader to crash.

Monolix2019:
![image](https://user-images.githubusercontent.com/25454764/114691302-d0556c80-9d17-11eb-88b6-b508534e584e.png)

Monolix2020:
![image](https://user-images.githubusercontent.com/25454764/114691331-d9463e00-9d17-11eb-81aa-07afbc5910d1.png)

In v2020, there are no spaces in the statement
file='warfarin_data3.csv'
which messes up the reader.

The controller creation with pmx_mlx (or pmx) works fine.

**Comment by agstudy** [comment]
the error because the parser use " = " to split the monolix file. 
As a workaround you can make the parser replace "file=" by "file = " before splitting.

Something like should work: 

    dat[grepl("file=",line),`line := gsub("file=","file = ",line)]

You should add this to parse_mlxtran function in [parse_mlxtran](https://github.com/ggPMXdevelopment/ggPMX/blob/de10f6168dd814b1dad62ecaea65bd5821f9119f/R/utils.R) just before this line :

      dat[, c("key", "value") := tstrsplit(dat$line, " = ")]

**Comment by mattfidler** [comment]
Thanks @agstudy

**Comment by tynesjo** [comment]
Thanks for the suggested fix @agstudy

It has been possible to
1. reproduce the error
2. implement and test the suggested fix

Pull request forthcoming (ETA today)
