### ISSUE TITLE
pmx_plot_individual: line not plotted until last time point when NOT using finegrid

### ISSUE THREAD

**Issue by baltcir1** [ggPMXdevelopment/ggPMX#200]
Version 1.2.6:

`pmx_plot_individual` doesn't plot the line until the last time point when NOT using finegrid (`use.finegrid = FALSE`)

**To reproduce:**
```
ctr %>% pmx_plot_individual(which_pages = "all",
                            facets = list(nrow = 7, ncol = 3),
                            pred_line = list(size = 0), 
                            ipred_line = list(size = 0.5),
                            point = list(color = "red"), scale_y_log10 = TRUE,
                            labels = list(x="Time (days)", y="Concentration (ng/ml)"),
                            use.finegrid = FALSE,
                            print=TRUE)
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/25454764/152701444-a8ea4244-2541-4f19-ad7b-145f33ec18d9.png)

**Comment by tynsci** [comment]
- Bug **reproduced**
- Output differences seems related to a different split of points into accepted/ignored

##### Minimal example

```
ctr <- theophylline()

p_broken <- pmx_plot_individual(
  ctr=ctr,
  pred_line = list(size = 0), 
  ipred_line = list(size = 0.5),
  use.finegrid = FALSE,
  print=TRUE
)


p_works <- pmx_plot_individual(
  ctr=ctr,
  pred_line = list(size = 0), 
  ipred_line = list(size = 0.5),
  use.finegrid = TRUE,
  print=TRUE
)
```

##### Screenshots

### Broken

![p_broken](https://user-images.githubusercontent.com/90842492/169283703-f431a60b-3a19-4774-89f8-f4185be0d0aa.png)


### Works


![p_works](https://user-images.githubusercontent.com/90842492/169283740-b60d7d2e-7edb-409b-b64e-698ff79d66c8.png)

**Comment by tynsci** [comment]
**Cause**:

- if `finegrid=TRUE` then the `IND` data set for the controller is used
- otherwise the `predictions` data set is used
- to decide whether or not to include an observation a column `isobserv` is added to the data
- if TIME (of observation) >= max time from predictions for that ID, then the observation is *excluded*
     - however this comparison does not take into account that the TIME observations in `predictions` are rounded, whilst in IND they are not
- therefore rounding is applied to the comparison in the merge request

**Note**:

- this fix  assumes that TIME values in `predictions` are always rounded to nearest integer value

**Screenshot**:

- distribution of time values for predictions below (all rounded to nearest integer):

```
theophylline()[["data"]][["predictions"]][["TIME"]] %>% table
``` 

![dist](https://user-images.githubusercontent.com/90842492/169485387-7f01a006-22aa-4e2e-8634-f0691a5b69be.png)

**Comment by mattfidler** [comment]
This could  be  OK, I'm nervous about the rounding solution @biethbr1 @baltcir1 what do you think.

**Comment by tynsci** [comment]
good point, @mattfidler 
**Suggestion**:
- Instead of _assuming_ rounding to 0 decimal places, check the number of significant decimal places in each data set (with non-0 values) and use that for rounding before comparison
    - implementation detail: can be achieved using `as.character`, `substr`, `nchar for example

**Comment by mattfidler** [comment]
We could, that would be better.  Perhaps we can add the option to configure and/or turn off too?  I can still imagine situations where it isn't  working properly.
