### ISSUE TITLE
Strange legend of pmx_plot_iwres_dens()

### ISSUE THREAD

**Issue by baltcir1** [ggPMXdevelopment/ggPMX#204]
Version 1.2.6: strange legend
`ctr %>% pmx_plot_iwres_dens()`

![image](https://user-images.githubusercontent.com/25454764/154171796-dc9f670c-9ffb-42ff-bffb-6c1c0170e53a.png)

Disappears when using `ctr %>% pmx_plot_iwres_dens(is.legend = FALSE)` (good thing!)

**Comment by biencan1** [comment]
Independently reproduced by Andrzej in ggPMX 1.2.8

**Comment by tynsci** [comment]
The problem was caused by legend guides being applied multiple places in the `plot_pmx.pmx_dens` function.

Pull request #280 addresses this.

- legend guides are still default but can be turned off by passing `is.legend=FALSE`
- color and linetype aesthetics are combined into one guide
- custom color and linetype are reflected in the guide
- no other aesthetics are included in the guide

## Examples

```
theophylline() %>% pmx_plot_iwres_dens
```
![p1](https://user-images.githubusercontent.com/90842492/198242812-e4f27eba-17fa-45a8-b86a-dea371d2bde3.png)

```
theophylline() %>% pmx_plot_iwres_dens(is.legend=FALSE)
```
![p2](https://user-images.githubusercontent.com/90842492/198242776-37b77e93-90ae-49c9-946a-fade6a1bc281.png)

```
theophylline() %>%
pmx_plot_iwres_dens(
  var_line=list(colour="darkblue", linetype=1),
  snd_line=list(colour="goldenrod")
)
```
![p3](https://user-images.githubusercontent.com/90842492/198242738-11a4deae-28b0-4fde-b4b5-f6c4281f7613.png)


```
theophylline() %>%
pmx_plot_iwres_dens(
  is.legend=FALSE,
  var_line=list(colour="darkblue", linetype=1),
  snd_line=list(colour="goldenrod", linetype=4)
)
```
![p4](https://user-images.githubusercontent.com/90842492/198242682-5acb6358-03c0-4e77-aecd-8eae7f6c06ec.png)
