### ISSUE TITLE
VPCs are not plotted correctly in the standard report in ggPMX 1.2.8

### ISSUE THREAD

**Issue by biencan1** [ggPMXdevelopment/ggPMX#263]
The VPC plots generated using standard report don't look right. Please find below an example of a unstratified VPC plot: 

![image](https://user-images.githubusercontent.com/73995818/189601068-db7eb496-5cf9-49b9-8929-84b6873fe4ff.png)

And an example of a stratified plot from the same standard report:
![image](https://user-images.githubusercontent.com/73995818/189601136-d9163a53-476f-43e8-af0c-a1aaa2882b46.png)

Just to compare I used the following R-code to generate a stratified VPC presented below:

```
set.seed(1234)
ctr %>%
pmx_plot_vpc(
  bin=pmx_vpc_bin(style = "jenks", within_strat = TRUE),
  strat.facet = "TRT",
  is.draft=FALSE,
  use.abbrev = TRUE,
  bloq=pmx_bloq(cens="BLOQ",colour="red",size=1),    ########## doesn't work
  labels = list(title = "Percentile VPC by dose level"),      ########## doesn't work correctly
  facets=list(scales="free")
) +
geom_hline(
  yintercept=0.5,
  linetype="dashed",
  color = "red"
) #LLOQ (lower limit of quantification)
```

![image](https://user-images.githubusercontent.com/73995818/189601712-ea766256-7c66-40bd-99e7-d06e829a61e3.png)

**Comment by baltcir1** [comment]
I would advise playing with the binning. This usually solves the issue. For example, fixed bins can be specified by the user.

**Comment by tynsci** [comment]
## Reproducibility

It has been possible to confirm the reported plotting behavior.

The difference between the plot outputs of the standard report and that from the custom command are due to the argument line `bin=pmx_vpc_bin(style="jenks", within_strat=TRUE)`.

## Solutions

To achieve a similar plot output in the report there are two approaches:

### 1. Update controller to use binning for VPC

For example run:

`pmx_update(ctr, "pmx_vpc", bin=pmx_vpc_bin(within_strat=TRUE, style="jenks"))`

here `ctr` is the controller object.

- this causes all subsequent VPC plotting of this controller to use the newly specified binning 

### 2. Use a custom template with binning specified

The output template can be modified for VPC plots. For example below the standard `pmx_plot_vpc` command used is modified:

#### Before

```{r}
ctr %>% pmx_plot_vpc
```

#### After (applying "jenks" style binning)

```{r}
ctr %>% pmx_plot_vpc(
  bin=pmx_vpc_bin(within_strat=TRUE, style="jenks")
)
```

## Resolution

- the above functionality will be added to the documentation

**Comment by tynsci** [comment]
- using binning as default (*quantile* algorithm) for VPC plots in template has been added to pull request

(@biencan1)
