### ISSUE TITLE
check upcoming ggplot 3.4.0

### ISSUE THREAD

**Issue by mattfidler** [ggPMXdevelopment/ggPMX#271]
`devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')`

**Comment by tynsci** [comment]
#### Steps completed
- review of 3.4.0 ggplot2 features
- running ggPMX tests with ggplot2 installed

#### Summary of changes
- `linewidth` instead of `size` - size still can be used (so no errors should appear in ggPMX plots (only warnings) (have checked)), but linewidth is better in case there are multiple size values for lines thicknesses. It would be better to change size to linewidth to avoid warnings

-  polygon line width in geom_sf() default was changed from 0.5 to 0.2

-  errors & warnings were rewritten (not important for ggPMX)

-  qplot, ..var.., stat() were deprecated (not used in ggPMX)

-  other changes as well are not important for ggPMX

#### Conclusion
- only major thing which should be changed is `linewidth` usage
- suggest usage of code snippet above

#### Next
- pull request forthcoming
