### ISSUE TITLE
How to handle zero values when plots are on log scale

### ISSUE THREAD

**Issue by KZRKZR** [ggPMXdevelopment/ggPMX#87]
Check how this is handled now:
are the points removed from the dataset before plotting?

This should match the current functioning of:
`ggplot2::scale_x_log_10` and `ggplot2::scale_y_log_10`

Verify empirically how it works and consider whether some warning/documentation/message is needed.

**Comment by agstudy** [comment]
Generally zeros are not removed. ggplot2::sacle_x_log deals generally well with zeros. 
The only exception is with finegrid. We keep only positive TIME>0. 

What do you mean by empirically here?

**Comment by mattfidler** [comment]
`ggplot2` adds dots to the bottom of the plot;  Perhaps they should be annotated in some way for clarity?  Or an option to remove the `TIME==0` points?

**Comment by tynsci** [comment]
- the current behavior is that log transformations cause nonpositive values to be dropped and there being no indication on the plot that this has happened

### Example
`pmx_plot_iwres_time(theophylline())`
![nonlog](https://user-images.githubusercontent.com/90842492/216235450-fbe2a516-f344-4217-826a-7361bd9cc5e0.png)


`pmx_plot_iwres_time(theophylline(), scale_x_log10=TRUE, scale_y_log10=TRUE)`

![log](https://user-images.githubusercontent.com/90842492/216235520-3dd6b5e4-a38e-45c4-a45f-dc8ca9f30899.png)

- note that the negative values on the x-axis here are due to transformations of TIME in the interval (0,1)

### Suggestion
- will add warning that data may be dropped from plot due to log transformations
